language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip

env:
  - GO111MODULE=on

services:
  - rabbitmq

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  # - go test -v ./...
  - go test -v .
  - go test -v ./encoderext/*
  - go test -v ./sentryext/*
  - go test -v ./cachext/*
  - go test -v ./busext/*
