language: go
go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
env:
  - GO111MODULE=on
cache:
  directories:
    - $GOPATH/pkg/mod
dist: xenial
addons:
  apt:
    packages:
      - rabbitmq-server
services:
  - rabbitmq
  - redis-server
  - mysql
before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
  - mysql -e 'CREATE DATABASE gobay DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
script:
  - golangci-lint run --timeout=10m --skip-dirs=testdata --tests=false
  - go test -v -count=1 ./...
